format: true
use-escaping: true

arb-dir: lib/l10n/translations
template-arb-file: en.arb

output-dir: lib/l10n
output-class: PlumeLocalizations
output-localization-file: plume_localizations.g.dart

untranslated-messages-file: untranslated.txt